
....

# The following section redirects HTTP requests by any URL to
# auth.dot.com authentication server. The same config should be
# made for SSL-enabled setups.

NameVirtualHost auth.mydomain.com:80

<VirtualHost auth.mydomain.com:80>
        ServerName auth.mydomain.com
        ServerAdmin postmaster@auth.mydomain.com
        RewriteEngine on
        RewriteCond %{REQUEST_URI} !^/cgi-bin/sweet*
        RewriteRule     ^(.*)$  http://auth.mydomain.com/cgi-bin/sweetspot.cgi [R=302,L]
</VirtualHost>

<VirtualHost _default_:80>
        ServerName redirect
        ServerAdmin postmaster@auth.mydomain.com
        RewriteEngine   on
        RewriteRule   ^(.*)$  http://auth.mydomain.com/cgi-bin/sweetspot.cgi?url=http://%{HTTP_HOST}%{REQUEST_URI}%{QUERY_STRING} [R=302,L]
</VirtualHost>

....