# Sweetspot daemon configuration

# inner interface name (which is close to users)
inner-interface bond0.12
inner-gw-ip 10.40.15.39
# outer interface name (which is close to Internet)
outer-interface bond0.2
outer-gw-ip 194.154.70.109
# user IP CIDR (addresses anyhow assigned to user computers)
#user-networks 127.0.0.0
user-networks 172.19.1.1/30

# SNAT public networks
snat-public-networks 62.141.101.62/32

# authentication server address
uam-server-address 194.154.70.109
#uam-server-address 127.0.0.1
# authentication server port
uam-server-port 3993

# authentication server shared secret (auth client must have the same)
uam-secret 1234567890

# report UAM errors back to client (obsolete)
#uam-report-errors 1

# Detail file accounting
acct-detail-file /var/sweetspot/detail

# Interim accounting interval (in secs)
acct-interim-interval 300

# NAS-IP-Address to report in acct detail file
#acct-nas-ip-address 127.0.0.1

# Packet filters directory
filter-dir /usr/local/etc/sweetspot/filters
#filter-dir ../doc/filters
# Captive filter
filter-anonymous anonymous

# Enable this if your captive portal resides on a dedicated host
#ignore-outgoing-packets 1


thread_qnty 16
uam-thread-qnty 1

local-networks 169.254.128.254/30
