# Sweetspot UAM client configuration

# authentication server group (comma-separated list)
uam-server-group 127.0.0.1:3993

# originate client message from this address
#uam-client-address 0.0.0.0

# UAM client receive timeout (values < 100 are seconds, larger - microseconds)
#uam-client-timeout 1

# authentication client shared secret (auth server must have the same)
uam-secret 1234567890
